trigger:
- main

stages:
- stage: Terraform_init_plan

  pool:
    vmImage: ubuntu-latest

  jobs:
 
  - job: terraform_init_plan

    steps:
    
    - task: TerraformInstaller
      displayName: install terraform
      inputs:
        terraformVersion: latest

    - task: TerraformCLI
      displayName: 'terraform init'
      inputs:
        command: init
        backendType: local
        backendServiceArm: 'My Azure Service Connection'
  
  
    
